# Files/directories to exclude from tree visualization
excluded_from_file_tree = [
  ".nuxt",
  ".git",
  ".output",
  "node_modules",
  "build",
  "project-context.xml"
]

# Files/directories to completely ignore
ignored_paths = [
  ".nuxt",
  ".output",
  "yarn.lock",
  "node_modules",
  ".git",
  "build",
  "dist",
  "package-lock.json",
  "project-context.xml"
]

# Paths to include in XML content
included_paths = [
  # ".claude/commands/nextSteps.md",
  # ".claude/settings.local.json",
  # ".editorconfig",
  # ".eslintignore",
  # ".eslintrc.json",
  # ".prettierrc.js",
  # ".project-context.toml",
  # "PLAN.md",
  "README.md",
  # "claude.md",
  "package.json",
  "src/config.ts",
  "src/index.ts",
  "tsconfig.json"
]